Image upload to S3 using axios, implemented with React front-end.
CloudClub-uoft/GuessTheLocation pull request #11
Opened 2024-01-31 20:27 UTC by zhangbrady4

https://github.com/CloudClub-uoft/GuessTheLocation/assets/127697715/85307944-16e8-4a8e-bb39-901ca5a0bce9

2024-02-01 04:54 UTC, qingyuan-wu requested changes

2024-02-01 04:54 UTC, qingyuan-wu commented on server/config/CloudClub.png
Can we remove this image? Seems unused

2024-02-01 04:54 UTC, qingyuan-wu commented on server/config/s3setup.js
> +*/
Is this used? If not can we remove?

2024-02-01 04:54 UTC, qingyuan-wu commented on server/server.js
> +app.set("view engine", "ejs")
want to remove this as we're not using ejs

2024-02-01 04:54 UTC, qingyuan-wu commented on server/server.js
> +const s3Client = require("./config/s3setup")
can we remove unused code?

2024-02-01 04:54 UTC, qingyuan-wu commented on server/server.js
> +app.use("/uath", authRouter);
hmm typo here?

2024-02-01 04:54 UTC, qingyuan-wu commented on server/views/uploaddone.ejs
> +<!DOCTYPE html>
Let's remove the entire `views` folder since we're not using ejs?

2024-02-01 04:54 UTC, qingyuan-wu commented on client/src/pages/WritePost.jsx
> +          {/* <form action="/postupload" method="POST" encType="multipart/form-data"> */}
Let's remove unused code (same as above/below)

2024-02-06 06:46 UTC, zhangbrady4 commented
Removed code for EJS and other unused code as requested in latest commit

2024-02-09 01:53 UTC, merged